[profile.default]
src = "src"
out = "out"
libs = ["lib", "../fuzzlib"]

evm_version = "cancun"
solc = "0.8.28"
optimizer = false
optimizer-runs = 0
via-ir = false

ffi = true
fs_permissions = [{ access = "read", path = "./deployments" }]

[profile.deploy]
evm_version = "cancun"
solc = "0.8.28"
optimizer = true
optimizer-runs = 50
via-ir = true


[fuzz]
runs = 10

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
